name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - run: bash build.sh
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: doom-alpine
          path: dist
